version: '3'

networks:
  whaticket:

services:

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    environment:
      - DB_HOST=postgres
      - DB_DIALECT=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=${POSTGRES_PASSWORD:-strongpassword}
      - DB_NAME=${POSTGRES_DATABASE:-whaticket}
      - JWT_SECRET=${JWT_SECRET:-3123123213123}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET:-75756756756}
      - BACKEND_URL=${BACKEND_URL:-http://localhost}
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:3000}
      - PROXY_PORT=${PROXY_PORT:-8080}
    ports:
      - ${BACKEND_PORT:-8080}:3000
    volumes:
      - ./backend/public/:/usr/src/app/public/
    networks:
      - whaticket

  frontend:
    ports:
      - ${FRONTEND_PORT:-3000}:80
      - ${FRONTEND_SSL_PORT:-3001}:443
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    environment:
      - URL_BACKEND=backend:3000
      - REACT_APP_BACKEND_URL=${BACKEND_URL:-http://localhost}:${PROXY_PORT:-8080}/
      - FRONTEND_SERVER_NAME=${FRONTEND_SERVER_NAME}
      - BACKEND_SERVER_NAME=${BACKEND_SERVER_NAME}
    volumes:
      - ./ssl/certs/:/etc/nginx/ssl/
      - ./ssl/www/:/var/www/letsencrypt/
    networks:
      - whaticket

  postgres:
    image: postgres:${POSTGRES_VERSION:-15}
    volumes:
      - ./.docker/data/:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE:-whaticket}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-strongpassword}
      - TZ=${TZ:-America/Fortaleza}
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    restart: always
    networks:
      - whaticket