import { Router } from "express";

import userRoutes from "./userRoutes";
import authRoutes from "./authRoutes";
import settingRoutes from "./settingRoutes";
import contactRoutes from "./contactRoutes";
import ticketRoutes from "./ticketRoutes";
import whatsappRoutes from "./whatsappRoutes";
import messageRoutes from "./messageRoutes";
import whatsappSessionRoutes from "./whatsappSessionRoutes";
import queueRoutes from "./queueRoutes";
import quickAnswerRoutes from "./quickAnswerRoutes";
import apiRoutes from "./apiRoutes";
import tagRoutes from "./tagRoutes";
import teamRoutes from "./teamRoutes";
import departmentRoutes from "./departmentRoutes";
import twoFactorRoutes from "./twoFactorRoutes";
import contactDedupRoutes from "./contactDedupRoutes";
import contactLGPDRoutes from "./contactLGPDRoutes";
import slaRoutes from "./slaRoutes";
import reopenReasonRoutes from "./reopenReasonRoutes";
import ticketRatingRoutes from "./ticketRatingRoutes";
import npsRoutes from "./npsRoutes";
import internalChatRoutes from "./internalChatRoutes";
import mediaLibraryRoutes from "./mediaLibraryRoutes";
import scheduledMessageRoutes from "./scheduledMessageRoutes";
import messageTemplateRoutes from "./messageTemplateRoutes";
import pushRoutes from "./pushRoutes";
import webhookRoutes from "./webhookRoutes";
import whiteLabelRoutes from "./whiteLabelRoutes";
import birthdayRoutes from "./birthdayRoutes";
import campaignRoutes from "./campaignRoutes";
import boardRoutes from "./boardRoutes";
import ticketLaneRoutes from "./ticketLaneRoutes";
import personalKanbanRoutes from "./personalKanbanRoutes";
import pipelineRoutes from "./pipelineRoutes";
import dealRoutes from "./dealRoutes";
import leadRoutes from "./leadRoutes";
import flowRoutes from "./flowRoutes";
import flowWebhookRoutes from "./flowWebhookRoutes";

const routes = Router();

routes.use(userRoutes);
routes.use("/auth", authRoutes);
routes.use(settingRoutes);
routes.use(contactRoutes);
routes.use(ticketRoutes);
routes.use(whatsappRoutes);
routes.use(messageRoutes);
routes.use(whatsappSessionRoutes);
routes.use(queueRoutes);
routes.use(quickAnswerRoutes);
routes.use(tagRoutes);
routes.use(teamRoutes);
routes.use(departmentRoutes);
routes.use(twoFactorRoutes);
routes.use(contactDedupRoutes);
routes.use(contactLGPDRoutes);
routes.use(slaRoutes);
routes.use(reopenReasonRoutes);
routes.use(ticketRatingRoutes);
routes.use(npsRoutes);
routes.use(internalChatRoutes);
routes.use(mediaLibraryRoutes);
routes.use(scheduledMessageRoutes);
routes.use(messageTemplateRoutes);
routes.use(pushRoutes);
routes.use(webhookRoutes);
routes.use(whiteLabelRoutes);
routes.use(birthdayRoutes);
routes.use(campaignRoutes);
routes.use(boardRoutes);
routes.use(ticketLaneRoutes);
routes.use(personalKanbanRoutes);
routes.use(pipelineRoutes);
routes.use(dealRoutes);
routes.use(leadRoutes);
routes.use(flowRoutes);
routes.use(flowWebhookRoutes);
routes.use("/api/messages", apiRoutes);

export default routes;
